"""Rename _id to id in User and Loan models and fix typo

Revision ID: 61008386ac48
Revises: 3f9b6a36dc9c
Create Date: 2025-11-01 10:19:38.355765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61008386ac48'
down_revision = '3f9b6a36dc9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('return_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_data', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('return_date')

    # ### end Alembic commands ###
