"""Add full columns to Book model

Revision ID: 9d90b03f0533
Revises: 65bbf65e3658
Create Date: 2025-10-18 18:05:53.417711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d90b03f0533'
down_revision = '65bbf65e3658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn', sa.String(length=13), nullable=False))
        batch_op.add_column(sa.Column('publication_date', sa.Date(), nullable=True))
        batch_op.drop_constraint(batch_op.f('books_ISBN_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['isbn'])
        batch_op.drop_column('ISBN')
        batch_op.drop_column('publication_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication_data', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ISBN', sa.VARCHAR(length=13), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('books_ISBN_key'), ['ISBN'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('publication_date')
        batch_op.drop_column('isbn')

    # ### end Alembic commands ###
